services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-chal02
    working_dir: /var/www/html
    ports:
      - "80:80"
    command: ["php", "-S", "0.0.0.0:80"]